fix: add 'use client' directive to Trending component
Error: Event handlers cannot be passed to Client Component props
Cause: BetaTrending uses onClick but wasn't marked as Client Component

Fix: Added 'use client' directive at top of file
Now the onClick handlers work properly.